### ISSUE TITLE
1RSS telemetry inverted on both 915M and 2.4G module

### ISSUE THREAD

**Issue by Pierre-Antoine2707** [BETAFPV/ExpressLRS#2]
## Current Behavior

1RSS telemetry is inverted : -127dbm (perfect link) to -1dbm (failsafe)
It happens on both 915M and 2.4G module on Radiomaster TX16S, with ELRS 1.1 installed in RX

## Steps to Reproduce

1.

2.

3.

4.

## Your Environment

- TX hardware:
- RX hardware:
- Handset model:
- OpenTX version (including nightly number)
- ExpressLRS version (TX & RX MUST MATCH):
- Packet Rate:
- Telemetry Ratio:
- user_defines:

**Comment by HWT662988** [comment]
Hi,Pierre-Antoine2707
I'm really sorry for replying so late.thanks for finding this bug, you can try the latest **master-betafpv-oled-menu** branch, it was fixed by this:[#2](https://github.com/BETAFPV/ExpressLRS/commit/ebf269fa252318f5f647d36916380f99e31cf910)
