### ISSUE TITLE
250mw or more doesn't work on 915M module (Ok on 2.4G module)

### ISSUE THREAD

**Issue by Pierre-Antoine2707** [BETAFPV/ExpressLRS#3]
## Current Behavior

activation of 250mW or 500 makes 915M module problem. After the power setting can be changed only on the module and no more with LUA script.
TX: Radiomaster TX16S

![IMG_3430](https://user-images.githubusercontent.com/81267481/142764791-22141f50-67e5-4555-b06e-d078882d8eb7.jpeg)

## Steps to Reproduce

1.

2.

3.

4.

## Your Environment

- TX hardware: Radiomaster TX16S
- RX hardware: Happymodel ES900
- Handset model:
- OpenTX version (including nightly number): Edge TX 2.5
- ExpressLRS version (TX & RX MUST MATCH): TX : this one RX: 1.1
- Packet Rate: 100Hz
- Telemetry Ratio: 1:64
- user_defines:

**Comment by HWT662988** [comment]
Hi,Pierre-Antoine2707.
I am sorry that i didn't find this problem under the same branch after a few tries，I can set the power to 250mw or 500mw and it works fine.

![image](https://user-images.githubusercontent.com/45007731/143804645-841bc01d-d058-4cfd-92a3-cb0c3a92c5c1.png)

The only difference is  the TX hardware my use is TX18S which is almost same  as TX16S.
Maybe you can try reloading your [ELRS.lua](https://github.com/ExpressLRS/ExpressLRS/blob/1.0.0/src/lua/ELRS.lua) and try again.
Best regards.
