### ISSUE TITLE
Micro TX LED Color Saving

### ISSUE THREAD

**Issue by bmfkai** [BETAFPV/ExpressLRS#5]
Is there any way to save the LED color so it's persistent through a power cycle?

I can set **currentColor** to 4, for example, and this gets me what I want but it would be nice if it would remember what was selected last before power cycling.  I'm assuming this will be intended behavior with **// static uint32_t lastColor = 0xFFFFFFFF;** in LED.h in a future update?

**Comment by HWT662988** [comment]
The color of the LED will be used to indicate the current system status in the 2.0 version release,So it will become automatic.
